
language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - cd ..
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git fetch
  - git branch -a
  - git checkout 2.4
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_ts=OFF -DBUILD_opencv_gpu=OFF -DBUILD_opencv_java=OFF ..
  - make -j2
  - cd ../..
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip gtest-1.7.0.zip
  - cd gtest-1.7.0
  - cmake .
  - make
  - pwd
  - cd ../elm
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update -qq
  # install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov
install:
  - sudo apt-get install -y libboost-system-dev libboost-filesystem-dev libboost-serialization-dev libboost-graph-dev libpcl-all lcov
before_script:
  - pwd
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DOpenCV_DIR=../opencv/build -DGTEST_ROOT=../gtest-1.7.0 -DCMAKE_INSTALL_PREFIX=install -DWITH_TEST_COVERAGE=ON ..
script:
  - make -j2
  - cd ./bin
  - ./run_elm_unittests
  - cd ..
after_success:
  - make elm_unittests_coverage
  - coveralls-lcov coverage.info
