language: cpp
compiler: gcc
before_install:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF ..
  - make -j
  - cd ../..
  - sudo apt-get update -qq
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip gtest-1.7.0.zip
  - cd gtest-1.7.0
  - cmake .
  - make
  - cd ..
  - sudo apt-get install -y libboost-system-dev libboost-filesystem-dev libboost-serialization-dev
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcl-all
before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF -DOpenCV_DIR=../opencv/build -DGTEST_ROOT=gtest-1.7.0 -DCMAKE_INSTALL_PREFIX=install ..
script: make
after_script:
  - cd build/bin
  - ./run_unittests
