version: 0.0.{build}
clone_depth: 10
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - C:\OpenCV249\opencv\build\x86\mingw_static
install:
  # install python packages (i.e. pip, numpy)
  #- powershell .\\ci\\appveyor\\install.ps1
  #- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - set PATH=C:\MinGW\bin;%PATH%
  - ls C:/Libraries/boost
  - ls C:/Libraries/boost/stage
  - ps: ls C:\
  - cmd: choco install opencv -y
  - cmd: SET APP_PATH=%CD%
  - ps: ls C:\OpenCV249\opencv\build\x86
  - ps: mkdir C:\OpenCV249\opencv\build\x86\mingw_static
  - ps: cd C:\OpenCV249\opencv\build\x86\mingw_static
  - ps: mv "C:\Program Files (x86)\Git\bin\sh.exe" "C:\Program Files (x86)\Git\bin\shxx.exe"
  - cmd: cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DBUILD_DOCS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_ts=OFF -DBUILD_opencv_gpu=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_ocl=OFF -DBUILD_opencv_nonfree=OFF -DBUILD_opencv_contrib=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_videostab=OFF -Wno-dev C:\OpenCV249\opencv\sources > NUL
  - cmd: mingw32-make > NUL
  - cmd: CD %APP_PATH%
  - cmd: CD ..
  - appveyor DownloadFile https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - 7z x .\gtest-1.7.0.zip -y > NUL
  - ps: cd gtest-1.7.0
  - cmd: cmake -G "MinGW Makefiles" . > NUL
  - cmd: mingw32-make > NUL
  - ps: mv "C:\Program Files (x86)\Git\bin\shxx.exe" "C:\Program Files (x86)\Git\bin\sh.exe"
  # return to repo dir
  - cmd: CD %APP_PATH%
before_build:
  - ps: mkdir ..\build
  - cmd: CD ..\build
  - ps: mv "C:\Program Files (x86)\Git\bin\sh.exe" "C:\Program Files (x86)\Git\bin\shxx.exe"
  - set PATH=C:\MinGW\bin;%PATH%
  - cmd: cmake -G "MinGW Makefiles" -DOpenCV_DIR=C:\OpenCV249\opencv\build\x86\mingw_static -DGTEST_ROOT=..\gtest-1.7.0 -DBOOST_ROOT=C:\Libraries\boost -DWITH_PCL=OFF -DWITH_MATIO=OFF ..\elm
  - ps: mv "C:\Program Files (x86)\Git\bin\shxx.exe" "C:\Program Files (x86)\Git\bin\sh.exe"
build_script:
  - set PATH=C:\MinGW\bin;%PATH%
  - cmd: mingw32-make
test_script:
  - ps: cd .\bin
  - cmd: .\run_elm_unittests.exe
# to run your custom scripts instead of provider deployments
deploy_script:
  - cmd: ECHO "NOTHING TO DEPLOY"
on_success:
  - cmd: ECHO "NOTHING TO DO ON SUCCESS"
