version: 0.0.{build}
install:
  - cmd: cmake --version
  - cmd: ECHO "INSTALL OPENCV:"
  - cmd: choco install opencv -y
  - appveyor DownloadFile https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - 7z x .\gtest-1.7.0.zip -y > NUL
  - cmd: CD gtest-1.7.0
  - cmd: cmake -G "MSYS Makefiles" .
  - cmd: make
  - cmd: dir C:\Libraries\boost
before_build:
  - cmd: SET APP_PATH=%CD%
  - cmd: IF EXIST C:\OpenCV* CD C:\OpenCV*
  - cmd: SET OPENCV_ROOT_PATH=%CD%\opencv
  - cmd: CD %APP_PATH%
build_script:
  - cmd: ECHO "BUILD"
test_script:
  - cmd: ECHO "TEST"
# to run your custom scripts instead of provider deployments
deploy_script:
  - cmd: ECHO "NOTHING TO DEPLOY"
on_success:
  - cmd: ECHO "NOTHING TO DO ON SUCCESS"
